# Generated by Django 5.1.5 on 2025-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport', models.FloatField()),
                ('electricity', models.FloatField()),
                ('diet', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], max_length=20)),
                ('total_emission', models.FloatField()),
            ],
        ),
    ]
